services:
  wordpress_config:
    ports:
      - '443:443'
      - '80:80'
    restart: always
    volumes:
      - '${WORDPRESS_PATH}'
      # - './certs:/etc/ssl/certs:ro'
      # - './default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf'
      # - './config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh'
      # Useful plugins to start with:
      - '../plugins/add-category-to-pages:/var/www/html/wp-content/plugins/add-category-to-pages'
      - '../plugins/elementor:/var/www/html/wp-content/plugins/elementor'
      - '../plugins/login-customizer:/var/www/html/wp-content/plugins/login-customizer'
      - '../plugins/restrict-user-access:/var/www/html/wp-content/plugins/restrict-user-access'
      - '../plugins/user-role-editor:/var/www/html/wp-content/plugins/user-role-editor'
      - '../plugins/wpzoom-elementor-addons:/var/www/html/wp-content/plugins/wpzoom-elementor-addons'
      - '../plugins/wpzoom-portfolio:/var/www/html/wp-content/plugins/wpzoom-portfolio'
      - '../plugins/simple-jwt-login:/var/www/html/wp-content/plugins/simple-jwt-login'
      # Custom plugins
      - '../plugins/wp-rs_share-variables-plugin:/var/www/html/wp-content/plugins/wp-rs_share-variables-plugin'
      - '../plugins/wp-rs_hide_rest_api:/var/www/html/wp-content/plugins/wp-rs_hide_rest_api'
      # Special configurations:
      - '../wp-config/.htaccess:/var/www/html/.htaccess'
      - '../wp-config/wp-config.php:/var/www/html/wp-config.php'

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      HOST_IP: ${HOST_IP}